// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMlP6PaSR19u5fLOWODE2Hs6BELQpe4bM',
    appId: '1:130435299738:web:fb0a113ec1e3a41e666223',
    messagingSenderId: '130435299738',
    projectId: 'pointofsale-fa2ce',
    authDomain: 'pointofsale-fa2ce.firebaseapp.com',
    storageBucket: 'pointofsale-fa2ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDskGXdo-7ferdf1qCCDYymdFGw09Gg_bQ',
    appId: '1:130435299738:android:dd233390fa8e163d666223',
    messagingSenderId: '130435299738',
    projectId: 'pointofsale-fa2ce',
    storageBucket: 'pointofsale-fa2ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_rShso3yEZHDzZpJVl0zOqroN0RSeQ9w',
    appId: '1:130435299738:ios:1cf081640de55f3b666223',
    messagingSenderId: '130435299738',
    projectId: 'pointofsale-fa2ce',
    storageBucket: 'pointofsale-fa2ce.appspot.com',
    androidClientId: '130435299738-6ooqs7oh1cpa78o6ote6tko09d3jrrl5.apps.googleusercontent.com',
    iosClientId: '130435299738-qkr60jvrifdgmnu2k5b9b2s255vn5b00.apps.googleusercontent.com',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_rShso3yEZHDzZpJVl0zOqroN0RSeQ9w',
    appId: '1:130435299738:ios:1cf081640de55f3b666223',
    messagingSenderId: '130435299738',
    projectId: 'pointofsale-fa2ce',
    storageBucket: 'pointofsale-fa2ce.appspot.com',
    androidClientId: '130435299738-6ooqs7oh1cpa78o6ote6tko09d3jrrl5.apps.googleusercontent.com',
    iosClientId: '130435299738-qkr60jvrifdgmnu2k5b9b2s255vn5b00.apps.googleusercontent.com',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMlP6PaSR19u5fLOWODE2Hs6BELQpe4bM',
    appId: '1:130435299738:web:8db7ff72bce8b0df666223',
    messagingSenderId: '130435299738',
    projectId: 'pointofsale-fa2ce',
    authDomain: 'pointofsale-fa2ce.firebaseapp.com',
    storageBucket: 'pointofsale-fa2ce.appspot.com',
  );
}
